---
# handlers file for k8s_setup
- name: restart kubelet
  become: yes
  systemd:
    name: kubelet
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: restart containerd
  command: /bin/true
  notify:
    - Containerd | restart containerd
    - Containerd | wait for containerd

- name: Containerd | restart containerd
  become: yes
  systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon-reload: yes

- name: Containerd | wait for containerd
  become: yes
  command: "ctr images ls -q"
  register: containerd_ready
  retries: 8
  delay: 4
  until: containerd_ready.rc == 0
