galaxy_info:
  role_name: k8s_setup
  author: Raj Nagar
  description: Add host to K8-cluster
  company: APT Portfolio

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.1

  galaxy_tags: []

dependencies: []
